### ISSUE TITLE
Suggestion: making the library available in platformIo library manager

### ISSUE THREAD

**Issue by pkerspe** [krygacz/arduino-eiscp#2]
It could would be gerat to be able to install the library via the platformio library manager by adding a library.json file to the repo:
https://docs.platformio.org/en/latest/librarymanager/creating.html

and then registering it:
https://docs.platformio.org/en/latest/core/userguide/lib/cmd_register.html#cmd-lib-register

**Comment by krygacz** [comment]
Once I get the response parser working and make sure that the library is stable I will definitely do this, thanks!

**Comment by pkerspe** [comment]
In order to register you could add the following library.json file to the root of the repository:
```
{
    "name": "arduino-eiscp",
    "description": "Arduino library for controlling eISCP-based devices (eg. Onkyo and Pioneer receivers)",
    "keywords": "eISCP,Pioneer,Onkyo,Receivers,control,LAN",
    "authors": {
        "name": "Krystian Gaczyński",
        "maintainer": true
    },
    "repository": {
        "type": "git",
        "url": "https://github.com/krygacz/arduino-eiscp.git"
    },
    "version": "0.2.2",
    "license": "GPL-3.0-only",
    "frameworks": "arduino",
    "platforms": [
        "espressif32", "espressif8266"
    ],
    "dependencies": [
    ],
    "examples": [
        "[Ee]xamples/*/*.ino"
    ]
}
```

After that just register it using platformio CLI (takes about 1-2 days to get listed):
`platformio lib register https://raw.githubusercontent.com/krygacz/arduino-eiscp/master/library.json`

I can also issue the command, once the json file exists

**Comment by krygacz** [comment]
Thanks! Just committed the json file, will register in a minute
