### ISSUE TITLE
Bug: compile error on PlatformIO with ESP "use of local variable with automatic storage from containing function"

### ISSUE THREAD

**Issue by pkerspe** [krygacz/arduino-eiscp#3]
Unfortunately in platformIO a compiler Error is shown in an ESP32 Project:
```
Compiling .pio/build/esp32dev/libacd/eISCP/eISCP.cpp.o
lib/eISCP/eISCP.cpp: In member function 'int eISCP::send(String)':
lib/eISCP/eISCP.cpp:19:35: error: use of local variable with automatic storage from containing function
   uint32_t i2 = __builtin_bswap32(body.length());
                                   ^
lib/eISCP/eISCP.cpp:15:9: note: 'String body' declared here
  String body = "!1" + command + '\r';
         ^
*** [.pio/build/esp32dev/libacd/eISCP/eISCP.cpp.o] Error 1
```

**Comment by krygacz** [comment]
I'm using the arduino ide and did't get any errors with v0.1.0 on esp8266. I'll install platformio and see if I can fix it

**Comment by krygacz** [comment]
Just committed a fix, can you clone the repo and check if the error persists?

**Comment by pkerspe** [comment]
I can confirm that the fix is working, the code compiles now and I can send a command to receiver with ESP32 after compiling in platformIO.
Unfortunately the ESP32 generates a Kernel Panic right after issuing the command. I will open a separate Ticket. This ticket can be closed as fixed. Thx a lot for the quick reply
