### ISSUE TITLE
0.2.4 example not compiling due to missing declaration of "my_function"

### ISSUE THREAD

**Issue by pkerspe** [krygacz/arduino-eiscp#9]
the currently provided example code in the readme is not working/compiling due to a missing declaration of the function "my_function(eISCP_Message message)".

When adding the declaration e.g. in line 12
`void my_function(eISCP_Message message);`
the code compiles

**Comment by krygacz** [comment]
The strangest part is that the vscode arduino extension didn't throw any errors, not even a single warning when building/uploading the example :c  
Just pushed a commit to fix it
